Vue.component('app-panel', require('./app/Panel.vue'))
Vue.component('app-upload-file', require('./app/UploadFile.vue'))
Vue.component('app-per-page', require('./app/PerPage.vue'))
Vue.component('app-pagination', require('./app/Pagination.vue'))
Vue.component('app-table', require('./app/Table.vue'))
Vue.component('app-input', require('./app/Input.vue'))
Vue.component('app-table-panel', require('./app/TablePanel.vue'))
