Vue.component('app-panel', require('./app/Panel.vue'))
Vue.component('app-upload-file', require('./app/UploadFile.vue'))
Vue.component('app-page-size', require('./app/PageSize.vue'))
Vue.component('app-pagination', require('./app/Pagination.vue'))
Vue.component('app-table', require('./app/Table.vue'))
Vue.component('app-input', require('./app/Input.vue'))
